### ISSUE TITLE
wallets.rb:35-37: Let's make it smarter. Instead of...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#124] opened 2018-06-02 08:03 UTC
The puzzle `70-ffaafc4f` from #70 has to be resolved:

https://github.com/zold-io/zold/blob/d0e304b2142bc0e2e03a9a64a444c90144015762/lib/zold/wallets.rb#L35-L37

The puzzle was created by Yegor Bugayenko on 02-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment] 2018-06-02 08:03
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/zold-io/zold/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `zold-io/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-06-02 08:04
I'm not managing `zold-io/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment] 2018-06-02 18:41
Job [#124](https://github.com/zold-io/zold/issues/124) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-06-05 11:45
The job [#124](https://github.com/zold-io/zold/issues/124) assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1561145455); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mulev** [comment] 2018-06-05 12:28
@0crat @yegor256 [@IlyaUmanets](https://github.com/IlyaUmanets) looks like it's a duplicate of [#78](https://github.com/zold-io/zold/issues/78)

**Comment by 0crat** [comment] 2018-06-05 12:29
> @0crat @yegor256 [@IlyaUmanets](https://github.com/IlyaUmanets) looks like it's a duplicate of [#... ([here](https://github.com/zold-io/zold/issues/124#issuecomment-394690623))

@mulev Can't understand "@yegor256", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment] 2018-06-10 12:36
@ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2018-06-15 11:44
The user @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets) resigned from [#124](https://github.com/zold-io/zold/issues/124), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-06-15 11:44
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets)

**Comment by 0crat** [comment] 2018-06-24 18:43
The job [#124](https://github.com/zold-io/zold/issues/124) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1751868299); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-06-29 20:37
@mulev[/z](https://www.0crat.com/u/mulev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2018-07-04 18:48
The user @mulev[/z](https://www.0crat.com/u/mulev) resigned from [#124](https://github.com/zold-io/zold/issues/124), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-07-04 18:48
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mulev[/z](https://www.0crat.com/u/mulev)

**Comment by 0crat** [comment] 2018-07-07 14:34
The job [#124](https://github.com/zold-io/zold/issues/124) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1881436280); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment] 2018-07-09 09:35
@0crat wait

**Comment by 0crat** [comment] 2018-07-09 09:39
> @0crat wait ([here](https://github.com/zold-io/zold/issues/124#issuecomment-403419754))

@emilianodellacasa The impediment for [#124](https://github.com/zold-io/zold/issues/124) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment] 2018-07-09 15:13
@yegor256 this is a duplictate  of #78 - I think it should be closed

**Comment by yegor256** [comment] 2018-07-09 17:10
@0crat refuse

**Comment by yegor256** [comment] 2018-07-09 17:10
@emilianodellacasa you are right, closing

**Comment by 0crat** [comment] 2018-07-09 17:10
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/124#issuecomment-403551258))

@yegor256 The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#124](https://github.com/zold-io/zold/issues/124), please stop working. Reason for job resignation: Order was cancelled

**Closed by yegor256** 2018-07-09 17:10 UTC
Labels: bug, pdd, scope

**Comment by 0crat** [comment] 2018-07-09 17:30
Job `gh:zold-io/zold#124` is not assigned, can't get performer

**Comment by 0crat** [comment] 2018-07-09 17:30
The job [#124](https://github.com/zold-io/zold/issues/124) is now out of scope
