### ISSUE TITLE
notify about taxes after each PAY

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#79] opened 2018-05-28 06:28 UTC
Let's notify the user about the situation with taxes in the wallet, after each PAY operation.

**Comment by 0crat** [comment] 2018-05-28 06:28
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/yegor256/zold/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `yegor256/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-05-28 06:30
Job [#79](https://github.com/yegor256/zold/issues/79) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-05-28 06:30
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-05-28 06:35
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/zold/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment] 2018-06-26 12:39
@0crat assign @ledestin

**Comment by 0crat** [comment] 2018-06-26 12:40
> @0crat assign @ledestin ([here](https://github.com/zold-io/zold/issues/79#issuecomment-400292817))

@yegor256 The job [#79](https://github.com/zold-io/zold/issues/79) assigned to @ledestin[/z](https://www.0crat.com/u/ledestin), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1771251710); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-06-26 12:40
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-06-26 12:40
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ledestin** [comment] 2018-06-26 17:17
@yegor256 I suppose taxes are to be reported for users that run nodes?

**Comment by yegor256** [comment] 2018-06-26 17:24
@ledestin no, no. I mean, after I do `zold pay` in command line, I should see the result and then a new line with something like that:

```
$ zold pay 00000000000ff1ce 912ecc24b32dbe74 500 'for expenses'
ksfz6hOR@912ecc24b32dbe74
15
500.00ZLD arrived to 912ecc24b32dbe74: for expenses
The tax debt in 00000000000ff1ce is 0.01 ZLD (still acceptable)
```

**Comment by ledestin** [comment] 2018-06-26 17:29
As per guidelines https://github.com/zold-io/zold/issues/300 and https://github.com/zold-io/zold/issues/299. Not sure if I'm doing it right, after all, no such docs exist at all yet.

**Comment by ledestin** [comment] 2018-06-27 08:06
@yegor256 not sure if it's a good idea to add it here, but here's my PR: https://github.com/zold-io/zold/pull/301

**Comment by 0crat** [comment] 2018-07-01 14:38
@ledestin[/z](https://www.0crat.com/u/ledestin) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment] 2018-07-04 08:46
@yegor256 the puzzle [#342](https://github.com/zold-io/zold/issues/342) is still not solved.

**Closed** 2018-07-04 08:46 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-07-04 09:03
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by 0crat** [comment] 2018-07-06 12:47
The user @ledestin[/z](https://www.0crat.com/u/ledestin) resigned from [#79](https://github.com/zold-io/zold/issues/79), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-07-06 12:47
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by ledestin** [comment] 2018-07-06 22:36
@yegor256 no payment here?

**Comment by yegor256** [comment] 2018-07-07 22:41
@ledestin unfortunately :( The robot has no mercy

**Comment by ledestin** [comment] 2018-07-09 10:44
@yegor256 but wasn't the PR merged before the robot decided it was too late?

**Comment by yegor256** [comment] 2018-07-09 10:59
@ledestin PR has nothing to do with this decision. The robot doesn't know how many PRs are required here. Keep in mind that one task may require many PRs before it's closed. When the ticket is closed -- the job is closed and should be paid. Until then, the robot doesn't care about PRs.

**Comment by ledestin** [comment] 2018-07-09 11:06
@yegor256 well, it was closed before being merged.

**Comment by yegor256** [comment] 2018-07-09 13:01
@ledestin I didn't understand the last message. Who was closed and who was merged?

**Comment by 0crat** [comment] 2018-07-10 09:39
The job [#79](https://github.com/zold-io/zold/issues/79) is now out of scope

**Comment by ledestin** [comment] 2018-07-10 09:55
@yegor256 sorry, this issue was closed by rultor, and then a PR was merged. I suppose, it all happened because the puzzle wasn't removed.

**Comment by 0pdd** [comment] 2018-11-02 15:01
@yegor256 the only puzzle [#342](https://github.com/zold-io/zold/issues/342) is solved here.
