### ISSUE TITLE
test - fake node instable

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#149] opened 2018-06-05 16:48 UTC
During the tests, I get many `599` errors. Sometimes the test cases work, then some fail cause the fake node is not running completely. We should work on that.

**Comment by 0crat** [comment] 2018-06-05 16:48
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-06-06 08:20
Job [#149](https://github.com/zold-io/zold/issues/149) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-06-06 08:21
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0crat** [comment] 2018-07-02 17:37
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2018-07-07 15:04
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#149](https://github.com/zold-io/zold/issues/149), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-07-07 15:04
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment] 2018-07-24 06:37
The job [#149](https://github.com/zold-io/zold/issues/149) assigned to @baybatu[/z](https://www.0crat.com/u/baybatu), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2050646363); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-07-29 07:38
@baybatu[/z](https://www.0crat.com/u/baybatu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment] 2018-11-14 08:35
@oltdaniel  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Closed by yegor256** 2018-11-14 08:35 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-11-14 09:10
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @baybatu[/z](https://www.0crat.com/u/baybatu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-11-14 09:10
The job [#149](https://github.com/zold-io/zold/issues/149) is now out of scope

**Comment by ypshenychka** [comment] 2018-11-14 09:43
@baybatu As far as there was no work done by you in scope of this issue (no PR created etc.), I should mark this ticket as of "bad" quality. Agree?

**Comment by baybatu** [comment] 2018-11-16 05:05
Actually, we don't know when this issue was resolved. If the issue is resolved before assigned to me, then it's totally normal that I could not create a PR and resolve issue :) Otherwise, it's ok to me. I think we need "neutral" thing instead of "bad" quality because it seems not depend on me :)

**Comment by baybatu** [comment] 2018-11-16 07:19
ok then, thanks

**Comment by ypshenychka** [comment] 2018-11-16 08:01
@0crat quality bad

**Comment by 0crat** [comment] 2018-11-16 08:01
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2018-11-16 08:02
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
