### ISSUE TITLE
Node hangs up

### ISSUE THREAD

**Issue by holly-fingers** [zold-io/zold#439] opened 2018-08-01 06:25 UTC
Starting a node with `zold node --invoice da8402c488c1def0 --host 62.149.12.97 --nohup` dies next day by stopping to accept HTTP connections to 4096 port, however process list is full of ruby threads and CPU + MEM are heavily used. From logs its seen that it tried to update `gem`(?) but it had no permissions as it was not running as `root`. Any way to make it run as non-root user?

```185.231.153.132:4096/0: same version 418b/0t of 7122788d4ed35756 there, in 14.47s
185.130.104.247:4096/7: same version 418b/0t of 7122788d4ed35756 there, in 13.3s
Thread Zold::Routines::Spread killed in 60.0s
185.209.160.27:4096: Net::ReadTimeout (HTTP code 599, instead of 200) in 64s; errors=6
Push finished to 14 nodes out of 15, total score for 9a856dac7d475014 is 0
185.209.160.27:4096: Net::ReadTimeout (HTTP code 599, instead of 200) in 64s; errors=7
Routine Zold::Routines::Reconnect #0 done in 192.88s
Thread Zold::Routines::Reconnect finished in 31.82s
Metronome stopped in 91.83s, 0 failures
Terminating the farm with 4 threads...
Cleanup thread killed in 0.0s
Thread 4:1018 finished in 0.39s
Thread 2:2105 finished in 0.1s
Thread 0:0617 finished in 0.1s
Thread 0:0618 finished in 0.1s
Farm stopped in 0.69s
Stopping async entrance, pool length is 8, queue length is 0
Async entrance was killed
Waiting for spread entrance to finish...
Spread entrance finished, thread killed
Nothing else left to read from #23990
Exit code of process #23990 is 0, was alive for 4 min: /usr/local/bin/zold node --invoice da8402c488c1def0 --host 62.149.12.97
Started process #24224 from process #23834: gem install zold
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
Nothing else left to read from #24224
Exit code of process #24224 is 256, was alive for 0 min: gem install zold
Started process #24229 from process #23834: /usr/local/bin/zold node --invoice da8402c488c1def0 --host 62.149.12.97
Home directory: /home/zold
```

**Comment by 0crat** [comment] 2018-08-01 06:25
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-08-01 06:26
@holly-fingers[/z](https://www.0crat.com/u/holly-fingers) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment] 2018-08-01 06:56
@holly-fingers just start it with `--nohup-command=sudo gem install zold` and that's it. But the problem is that you see many processes.. This is what should be fixed.

**Comment by yegor256** [comment] 2018-11-02 07:50
@holly-fingers This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Closed by yegor256** 2018-11-02 07:50 UTC

**Comment by 0crat** [comment] 2018-11-02 08:06
Job `gh:zold-io/zold#439` is not assigned, can't get performer

**Comment by 0crat** [comment] 2018-11-02 08:06
This job is not in scope
